---
- name: Install st2
  hosts: all
  roles:
    - name: Install mongodb
      role: mongodb
      vars:
        mongodb_version: 3.2
    - rabbitmq
    - postgresql
    - st2repo
    - name: Install and configure st2
      role: st2
      vars:
        st2_version: 2.1.0
        st2_revision: 16
    - st2mistral
    - nginx
    - st2web
    - nodejs
    - st2smoketests
